version: '3.8'

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_NAME=$DB_NAME
    ports:
      - $DB_PORT_LOCAL:$DB_PORT_DOCKER
    volumes:
      - db:/var/lib/postgresql/data

  app:
    image: sheerpeace-backend
    depends_on:
      - postgresdb
    build: ./sheerpeace-backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $PORT:$PORT_DOCKER
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASS
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT_DOCKER
    stdin_open: true
    tty: true

volumes:
  db:
