name: publish

on:
  push:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/sheerpeace-backend:latest

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login
      run: |
        echo "${{ secrets.PAT }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
    - name: Build and Publish Backend
      run: |
        IMAGE_NAME_LOWER=$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')/sheerpeace-backend:latest
        docker build . --tag ${{ env.REGISTRY }}/$IMAGE_NAME_LOWER
        docker push ${{ env.REGISTRY }}/$IMAGE_NAME_LOWER